/* Los artefactos de convergencia no tienen un esquema TypeScript propio aún. */
/* eslint-disable @typescript-eslint/no-explicit-any */
import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import type { Author, Catalog, Drink, Evidence, Recommendation, Work } from './content-types.ts'

type Proposal = { discovery_id: string; source_candidate_ids: string[]; author: { action: string; canonical_id: string; canonical_name: string }; work: { action: string; canonical_id: string | null; title: string | null }; drink: { action: string; canonical_id: string; name_es: string; aliases: string[]; recipe_plan: string }; recommendation: { relationship_type: Recommendation['relationship_type']; confidence: Recommendation['confidence']; headline_es: string; explanation_es: string }; evidence: { source_id: string; claim: string; locator: string; support_excerpt: string } }
type Result = { items: Proposal[] }
const root = resolve(import.meta.dirname, '..')
const base = resolve(root, 'data/research/book-convergence/three-literary-books')
const read = async <T>(path: string) => JSON.parse(await readFile(path, 'utf8')) as T
const write = async (path: string, value: unknown) => writeFile(path, `${JSON.stringify(value, null, 2)}\n`)
const add = <T extends { id: string }>(items: T[], item: T) => { if (!items.some(({ id }) => id === item.id)) items.push(item) }
const ids = ['002','003','004','006','007','008','011','012','013','014','015','016','017','018','019','020','021','022','023','024','027'].map((id) => `hallazgo-three-books-${id}`)
const nonAlcoholic = new Set(['natilla-hervida'])
const servingOnly = new Set(['vino-de-grosella', 'vino-de-diente-de-leon', 'cerveza-con-esencia-de-abeto', 'cerveza-de-caqui', 'cordiales', 'cerveza-pequena'])
const catalog = await read<Catalog>(resolve(root, 'data/source/catalog.json'))
const results = await Promise.all(['literary-eats-01.json', 'literary-eats-02.json'].map((file) => read<Result>(resolve(base, 'agent-results', file))))
const proposals = results.flatMap((result) => result.items)
if (proposals.length !== ids.length || new Set(proposals.map(({ discovery_id }) => discovery_id)).size !== ids.length || !ids.every((id) => proposals.some((item) => item.discovery_id === id))) throw new Error('Los resultados Luna no cubren exactamente los 21 hallazgos asignados.')
const added: string[] = []
for (const item of proposals) {
  if (item.author.action === 'create_minimal') { const author: Author = { id: item.author.canonical_id, slug: item.author.canonical_id, canonical_name: item.author.canonical_name, aliases: [item.author.canonical_name.split(' ').at(-1)!], featured_works: [], profile_status: 'minimal', status: 'published', reviewed_at: '2026-07-28' }; const before = catalog.authors.length; add(catalog.authors, author); if (catalog.authors.length > before) added.push(author.id) }
  if (item.work.action === 'create_minimal' && item.work.canonical_id && item.work.title) { const work: Work = { id: item.work.canonical_id, author_id: item.author.canonical_id, original_title: item.work.title, display_title_es: item.work.title, identifiers: {}, notes: 'Obra mínima identificada por Literary Eats; metadatos pendientes.', metadata_status: 'minimal' }; const before = catalog.works.length; add(catalog.works, work); if (catalog.works.length > before) added.push(work.id) }
  if (item.drink.action !== 'reuse') { const isServing = servingOnly.has(item.drink.canonical_id); const drink: Drink = { id: item.drink.canonical_id, name_es: item.drink.name_es, aliases: item.drink.aliases, category: isServing ? 'Bebida de servicio' : 'Preparación de la casa', alcoholic: !nonAlcoholic.has(item.drink.canonical_id), ingredients: isServing ? [] : [{ name: 'base de la casa', amount: 1, unit: 'porción' }], steps: isServing ? ['Sirve la bebida a la temperatura adecuada.'] : ['Prepara una versión contemporánea de la casa, separada de la fuente histórica.'], glassware: 'Vaso apropiado', recipe_note: item.drink.recipe_plan, recipe_status: isServing ? 'serving_only' : 'house' }; const before = catalog.drinks.length; add(catalog.drinks, drink); if (catalog.drinks.length > before) added.push(drink.id) }
  const recId = `${item.author.canonical_id}-${item.drink.canonical_id}-literary-eats`
  const evidenceId = `evidencia-${recId}`
  const recommendation: Recommendation = { id: recId, author_id: item.author.canonical_id, ...(item.work.action !== 'not_applicable' && item.work.canonical_id ? { work_id: item.work.canonical_id } : {}), drink_id: item.drink.canonical_id, relationship_type: item.recommendation.relationship_type, headline_es: item.recommendation.headline_es, explanation_es: item.recommendation.explanation_es, confidence: item.recommendation.confidence, evidence_ids: [evidenceId], editorial_status: 'published', reviewed_by: 'convergencia-tres-libros', reviewed_at: '2026-07-28' }
  const beforeRec = catalog.recommendations.length; add(catalog.recommendations, recommendation); if (catalog.recommendations.length > beforeRec) added.push(recId)
  const evidence: Evidence = { id: evidenceId, recommendation_id: recId, source_id: item.evidence.source_id, claim: item.evidence.claim, support_excerpt: item.evidence.support_excerpt, locator: item.evidence.locator, evidence_kind: 'bibliographic_reference', supports_claim: true, checked_at: '2026-07-28' }; const beforeEvidence = catalog.evidence.length; add(catalog.evidence, evidence); if (catalog.evidence.length > beforeEvidence) added.push(evidenceId)
}
catalog.discoveries = catalog.discoveries.filter(({ id }) => !ids.includes(id))
await write(resolve(root, 'data/source/catalog.json'), catalog)
const consolidated = await read<any>(resolve(base, 'consolidated-candidates.json'))
for (const candidate of consolidated.candidates) { const proposal = proposals.find((item) => item.source_candidate_ids.some((id) => candidate.source_candidate_ids.includes(id))); if (!proposal) continue; candidate.normalized.author_id = proposal.author.canonical_id; candidate.normalized.drink_id = proposal.drink.canonical_id; candidate.normalized.relationship_type = proposal.recommendation.relationship_type; if (proposal.work.canonical_id) candidate.normalized.work_id = proposal.work.canonical_id; candidate.convergence_status = 'promotion_ready'; candidate.decision_reason = ['Promovido tras revisión Terra: evidencia bibliográfica localizada, entidades mínimas y receta de la casa o servicio directo explícitos.'] }
await write(resolve(base, 'consolidated-candidates.json'), consolidated)
const sourceIds = new Set(proposals.flatMap(({ source_candidate_ids }) => source_candidate_ids))
for (const file of ['needs-review.json', 'promotion-ready.json']) { const artifact = await read<any>(resolve(base, file)); if (Array.isArray(artifact.items)) { if (file === 'needs-review.json') artifact.items = artifact.items.filter((item: any) => !sourceIds.has(item.source_candidate_id) && !ids.includes(item.convergence_id?.replace('three-books-', 'hallazgo-three-books-'))); else artifact.items.push(...proposals.map((item) => ({ source_candidate_id: item.source_candidate_ids[0], action: 'create_recommendation', canonical_record: `${item.author.canonical_id}-${item.drink.canonical_id}-literary-eats`, evidence_id: `evidencia-${item.author.canonical_id}-${item.drink.canonical_id}-literary-eats`, source_id: 'fuente-literary-eats', confidence: item.recommendation.confidence, justification: 'Promoción Terra desde normalización mecánica revisada.' }))) }; if ('count' in artifact) artifact.count = artifact.items.length; await write(resolve(base, file), artifact) }
const log = await read<any>(resolve(base, 'promotion-log.json')); log.batches.push({ batch_id: 'promotion-006-literary-eats-remaining', source_candidate_ids: proposals.flatMap(({ source_candidate_ids }) => source_candidate_ids), status: 'applied', ids_added: added, ids_updated: [], discoveries_removed_after_promotion: ids, validation: 'pending', errors: [] }); await write(resolve(base, 'promotion-log.json'), log)
const manifest = await read<any>(resolve(base, 'manifest.json')); manifest.final_counts.catalog = Object.fromEntries(['authors','works','drinks','recommendations','evidence','sources','discoveries'].map((key) => [key, (catalog as any)[key].length])); await write(resolve(base, 'manifest.json'), manifest)
console.log(`Promovidos ${proposals.length} hallazgos de Literary Eats.`)
