import { useState } from 'react'
import type { PublicAuthor } from '../scripts/content-types'
import { content } from './content/generated'
import { SearchBox } from './components/SearchBox'
import { AuthorSheet } from './components/AuthorSheet'

type Page = 'home' | 'method' | 'sources'
export function App() {
  const [selected, setSelected] = useState<PublicAuthor | null>(null)
  const [page, setPage] = useState<Page>('home')
  const showAuthor = (author: PublicAuthor) => { setSelected(author); setPage('home') }
  const randomAuthor = () => showAuthor(content.authors[Math.floor(Math.random() * content.authors.length)])
  const lightNavigation = selected !== null || page !== 'home'
  return <main><nav className={`site-nav${lightNavigation ? ' site-nav-light' : ''}`} aria-label="Navegación principal"><button type="button" className="wordmark" onClick={() => { setSelected(null); setPage('home') }}>Trago <i>y</i> Letra</button><div><button type="button" onClick={() => setPage('method')}>Método</button><button type="button" onClick={() => setPage('sources')}>Fuentes</button></div></nav>{selected ? <AuthorSheet author={selected} drinks={content.drinks} onClose={() => setSelected(null)} /> : page === 'home' ? <Home onSelect={showAuthor} onRandom={randomAuthor} /> : page === 'method' ? <Method /> : <Sources />}</main>
}
function Home({ onSelect, onRandom }: { onSelect: (author: PublicAuthor) => void; onRandom: () => void }) { return <><section className="hero"><div className="hero-inner"><p className="hero-kicker">Lecturas con procedencia</p><h1>Una bebida.<br /><em>Una historia.</em></h1><p className="hero-copy">Encuentra una compañía de lectura y conoce con claridad si el vínculo viene de una obra, una fuente biográfica o una decisión editorial.</p><SearchBox authors={content.authors} onSelect={onSelect} /><button type="button" className="random-button" onClick={onRandom}>Llévame a un autor al azar <span aria-hidden="true">↗</span></button></div><p className="hero-side">Sin inventar<br />la anécdota.</p></section><section className="principles"><p className="eyebrow">El criterio</p><h2>La procedencia no es una nota al pie.</h2><div><p>Publicamos sólo vínculos que puedan explicarse: una bebida documentada, una presencia identificable en una obra o un maridaje editorial rotulado como tal.</p><p className="responsible-note">Para mayores de edad. Si bebes, hazlo con responsabilidad.</p></div></section></> }
function Method() { return <section className="text-page"><p className="eyebrow">Cómo elegimos</p><h1>Claridad antes que leyenda.</h1><p>Preferimos textos y fuentes comprobables. También reservamos espacio para mitos simpáticos que siguen en circulación: en ese caso se rotulan de forma explícita y jamás se disfrazan de biografía segura.</p><dl><dt>Bebida documentada</dt><dd>Una fuente respalda consumo, preparación o preferencia; la redacción no va más lejos que la evidencia.</dd><dt>Aparece en la obra</dt><dd>La bebida se identifica en una escena y se indica su obra y localizador.</dd><dt>Según el mito</dt><dd>Una anécdota popular con una fuente localizable. Es parte del juego cultural, no un hecho confirmado.</dd><dt>Maridaje editorial</dt><dd>Una propuesta del equipo, visible como interpretación y no como hecho biográfico.</dd><dt>Abstinencia o recuperación</dt><dd>Se trata con sobriedad y puede llevar a una recomendación sin alcohol.</dd></dl><p>Las correcciones se revisan contra la fuente y se registran antes de publicar una actualización.</p></section> }
function Sources() { return <section className="text-page"><p className="eyebrow">Fuentes y créditos</p><h1>Un catálogo que se puede revisar.</h1><p>El catálogo público reúne fuentes revisadas para cada ficha. No contiene retratos, portadas ni textos completos de terceros.</p><ul className="source-list">{content.sources.map((source) => <li key={source.id}><strong>{source.title}</strong><span>{source.author_or_publisher} · {source.reliability_tier}</span></li>)}</ul><p>Textos de interfaz y recetas: Trago y Letra. Cada vínculo editorial se limita al alcance de su fuente.</p></section> }
